### ISSUE TITLE
How to uninstall elasticluster ?

### ISSUE THREAD

**Issue by Smahane** [elasticluster/elasticluster#671]
I installed it via the docker file. How to completely uninstall it?

Thank you,

**Comment by riccardomurri** [comment]
This should completely remove all traces of ElastiCluster from your system:

1. Remove the `elasticluster.sh` script
2. Remove the configuration and state directory: `rm -rf $HOME/.elasticluster`
3. Remove the Docker image: `docker rmi riccardomurri/elasticluster`
4. Remove the Docker package from the system (unless you're using it for other purposes).

May I still ask what drove you away from ElastiCluster?

**Comment by Smahane** [comment]
@riccardomurri  thank you.
I'm not giving up yet. I'm having issues getting it to work. Trying to see if reinstalling can fix the problem of:

"apps.googleusercontent.com.oauth.dat: No such file or directory
2019-12-19 12:00:19 a46689bb08c3 elasticluster[1] INFO Determined that provided credentials are not valid."

```

smahane@cloudshell:~ (zyme-cluster)$ ./elasticluster.sh -v start clustergold -n smahane-n1-cluster
Starting cluster `smahane-n1-cluster` with:
* 1 frontend nodes.
* 2 compute nodes.
(This may take a while...)
2019-12-19 12:00:19 a46689bb08c3 elasticluster[1] INFO Starting cluster nodes (timeout: 600 seconds) ...
2019-12-19 12:00:19 a46689bb08c3 elasticluster[1] INFO Starting node `frontend001` from image `https://www.googleapis.com/compute/v1/projects/r/global/images/smahane` with flavor n1-highcpu-64 ...
2019-12-19 12:00:19 a46689bb08c3 elasticluster[1] INFO Starting node `compute001` from image `https://www.googleapis.com/compute/v1/projects/r/global/images/smahane` with flavor n1-highcpu-64 ...
2019-12-19 12:00:19 a46689bb08c3 elasticluster[1] INFO Starting node `compute002` from image `https://www.googleapis.com/compute/v1/projects/zyme-cluster/global/images/smahane` with flavor n1-highcpu-64 ...
2019-12-19 12:00:19 a46689bb08c3 elasticluster[1] WARNING UserWarning: Cannot access /home/smahane_douyeb/.elasticluster/storage/634267315974-f0cilujsahhh9s2bfq0lrfic8u3k7b60.apps.googleusercontent.com.oauth.dat: No such file or directory
2019-12-19 12:00:19 a46689bb08c3 elasticluster[1] INFO Determined that provided credentials are not valid.
2019-12-19 12:00:19 a46689bb08c3 elasticluster[1] INFO Attempting to use Google Application Default Credentials.
2019-12-19 12:00:20 a46689bb08c3 elasticluster[1] ERROR Error creating instance `<HttpError 400 when requesting https://compute.googleapis.com/compute/v1/projects/zyme-cluster/zones/us-east1/instances?alt=json returned "Invalid value for field 'zone': 'us-east1'. Unknown zone.">`
2019-12-19 12:00:20 a46689bb08c3 elasticluster[1] ERROR Could not start node `compute001`: Error creating instance `<HttpError 400 when requesting https://compute.googleapis.com/compute/v1/projects/zyme-cluster/zones/us-east1/instances?alt=json returned "Invalid value for field 'zone': 'us-east1'. Unknown zone.">` -- <class 'elasticluster.exceptions.InstanceError'>
Traceback (most recent call last):
  File "elasticluster/cluster.py", line 580, in _start_node
    node.start()
  File "elasticluster/cluster.py", line 1319, in start
    **self.extra)
  File "elasticluster/providers/gce.py", line 531, in start_instance
    raise InstanceError("Error creating instance `%s`" % e)
InstanceError: Error creating instance `<HttpError 400 when requesting https://compute.googleapis.com/compute/v1/projects/zyme-cluster/zones/us-east1/instances?alt=json returned "Invalid value for field 'zone': 'us-east1'. Unknown zone.">`
```

**Comment by riccardomurri** [comment]
Given the traceback you posted, it seems that the critical error is rather this one:
```
Invalid value for field 'zone': 'us-east1'. Unknown zone.
```
Perhaps you requested a node type which is not available on zone `us-east1`?

**Comment by Smahane** [comment]
@riccardomurri  It worked. thank you so much. I missed that and was looking at the  credential error.
Does elasticluster create an NFS or any sort of shard directory between nodes in the cluster? is this something i can add to the configuration or it's done by default?

**Comment by manuelesimi** [comment]
us-east1 does not exist as Azure location.
From "az account list-locations -o table":

East US              37.3719     -79.8164     eastus
East US 2            36.6681     -78.3889     eastus2

**Comment by riccardomurri** [comment]
> Does elasticluster create an NFS or any sort of shard directory between nodes in the cluster? 

By default, directory `/home` is shared across the whole cluster.  You can add more by running a custom post-installation playbook.
