### ISSUE TITLE
Problem installing a GPU cluster on google cloud

### ISSUE THREAD

**Issue by ivandrodri** [elasticluster/elasticluster#690]
Hello,

I am trying to use elasticluster on google cloud for one of my projects and I have the following problem 
(my config file is below):

##############################################
##############################################

TASK [lmod : Perform OS-specific post-installation] ********************************************************************************************************************************************************
included: /home/elasticluster/share/playbooks/roles/lmod/tasks/postinst-Debian.yml for compute001, compute002, compute003, compute004

TASK [lmod : Create required directories] ******************************************************************************************************************************************************************
ok: [compute004] => (item=/etc/profile.d)
ok: [compute001] => (item=/etc/profile.d)
ok: [compute002] => (item=/etc/profile.d)
ok: [compute003] => (item=/etc/profile.d)
changed: [compute002] => (item=/etc/csh)
changed: [compute004] => (item=/etc/csh)
changed: [compute001] => (item=/etc/csh)
changed: [compute003] => (item=/etc/csh)
changed: [compute002] => (item=/etc/csh/login.d)
changed: [compute001] => (item=/etc/csh/login.d)
changed: [compute004] => (item=/etc/csh/login.d)
changed: [compute003] => (item=/etc/csh/login.d)

TASK [lmod : Ensure modulefiles directories are in MODULEPATH] *********************************************************************************************************************************************
skipping: [compute001]
skipping: [compute002]
skipping: [compute003]
skipping: [compute004]

TASK [lmod : Ensure modulefiles directories are in MODULEPATH] *********************************************************************************************************************************************
failed: [compute003] (item={u'dest': u'/etc/profile.d/01-modulepath.sh', u'src': u'etc/profile.d/01-modulepath.sh.j2'}) => {"ansible_loop_var": "item", "item": {"dest": "/etc/profile.d/01-modulepath.sh", "src": "etc/profile.d/01-modulepath.sh.j2"}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610042226.57-10432998064809 `\" && echo ansible-tmp-1610042226.57-10432998064809=\"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610042226.57-10432998064809 `\" ), exited with result 1", "unreachable": true}
failed: [compute003] (item={u'dest': u'/etc/csh/login.d/01-modulepath.csh', u'src': u'etc/profile.d/01-modulepath.csh.j2'}) => {"ansible_loop_var": "item", "item": {"dest": "/etc/csh/login.d/01-modulepath.csh", "src": "etc/profile.d/01-modulepath.csh.j2"}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610042227.11-164657505118398 `\" && echo ansible-tmp-1610042227.11-164657505118398=\"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610042227.11-164657505118398 `\" ), exited with result 1", "unreachable": true}
fatal: [compute003]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"ansible_loop_var": "item", "item": {"dest": "/etc/profile.d/01-modulepath.sh", "src": "etc/profile.d/01-modulepath.sh.j2"}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610042226.57-10432998064809 `\" && echo ansible-tmp-1610042226.57-10432998064809=\"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610042226.57-10432998064809 `\" ), exited with result 1", "unreachable": true}, {"ansible_loop_var": "item", "item": {"dest": "/etc/csh/login.d/01-modulepath.csh", "src": "etc/profile.d/01-modulepath.csh.j2"}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610042227.11-164657505118398 `\" && echo ansible-tmp-1610042227.11-164657505118398=\"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610042227.11-164657505118398 `\" ), exited with result 1", "unreachable": true}]}
changed: [compute001] => (item={u'dest': u'/etc/profile.d/01-modulepath.sh', u'src': u'etc/profile.d/01-modulepath.sh.j2'})
changed: [compute002] => (item={u'dest': u'/etc/profile.d/01-modulepath.sh', u'src': u'etc/profile.d/01-modulepath.sh.j2'})
changed: [compute004] => (item={u'dest': u'/etc/profile.d/01-modulepath.sh', u'src': u'etc/profile.d/01-modulepath.sh.j2'})
changed: [compute001] => (item={u'dest': u'/etc/csh/login.d/01-modulepath.csh', u'src': u'etc/profile.d/01-modulepath.csh.j2'})
changed: [compute002] => (item={u'dest': u'/etc/csh/login.d/01-modulepath.csh', u'src': u'etc/profile.d/01-modulepath.csh.j2'})
changed: [compute004] => (item={u'dest': u'/etc/csh/login.d/01-modulepath.csh', u'src': u'etc/profile.d/01-modulepath.csh.j2'})

NO MORE HOSTS LEFT *****************************************************************************************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************************************************
compute001                 : ok=99   changed=55   unreachable=0    failed=0    skipped=70   rescued=0    ignored=0   
compute002                 : ok=99   changed=55   unreachable=0    failed=0    skipped=70   rescued=0    ignored=0   
compute003                 : ok=98   changed=54   unreachable=1    failed=0    skipped=70   rescued=0    ignored=0   
compute004                 : ok=99   changed=55   unreachable=0    failed=0    skipped=70   rescued=0    ignored=0   
frontend001                : ok=139  changed=91   unreachable=0    failed=0    skipped=70   rescued=0    ignored=0   

2021-01-07 17:57:13 0fabb0dd4f32 elasticluster[1] ERROR Command `ansible-playbook --private-key=/home/.ssh/google_compute_engine /home/elasticluster/share/playbooks/main.yml --inventory=/home/.elasticluster/storage/slurm-gpu.inventory --become --become-user=root -e @extra_vars.yml` failed with exit code 2.
2021-01-07 17:57:13 0fabb0dd4f32 elasticluster[1] WARNING The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup`.
2021-01-07 17:57:13 0fabb0dd4f32 elasticluster[1] WARNING Cluster `slurm-gpu` not yet configured. Please, re-run `elasticluster setup slurm-gpu` and/or check your configuration

WARNING: YOUR CLUSTER `slurm-gpu` IS NOT READY YET!

Cluster name:     slurm-gpu
Cluster template: slurm-gpu
Default ssh to node: frontend001
- frontend nodes: 1
- compute nodes: 4

To login on the frontend node, run the command:

    elasticluster ssh slurm-gpu

To upload or download files to the cluster, use the command:

    elasticluster sftp slurm-gpu

############################################################
############################################################

 
 This is my CONFIG FILE (it is one of the examples include in the repository):

 #############################

#
# ElastiCluster example: SLURM cluster with GPUs on Google Cloud
#
# This is a complete and self-contained example that should get you
# started with running SLURM clusters with GPU-accelerated compute
# nodes on Google Cloud Engine.  Note that, as of Nov. 2017,
# GPU-enabled VMs are available only in few zones so you may not be
# able to run this example in your default region/zone.
#
# For more details, see:
# - http://googlegenomics.readthedocs.io/en/latest/use_cases/setup_gridengine_cluster_on_compute_engine/index.html#create-a-grid-engine-cluster-on-compute-engine
# - http://elasticluster.readthedocs.io/en/latest/configure.html
# - http://elasticluster.readthedocs.io/en/latest/playbooks.html#id5
#

# SLURM software to be configured by Ansible
#
# (There is nothing Google-specific in the "setup" section; in fact, it can be
# re-used verbatim with *any* cloud provider or base image)
[setup/slurm]
provider=ansible
frontend_groups=slurm_master
# the `cuda` role installs support for NVIDIA GPUs and the CUDA
# runtime and development toolkit
compute_groups=slurm_worker,cuda

# if the NVIDIA drivers are not installed correctly, you might need to
# ElastiCluster to reboot the nodes -- this is accomplished by the
# following variable setting. (ATM, needed on CentOS/RHEL but not on Ubuntu.)
#compute_var_allow_reboot=yes

# If nodes have multiple GPUs, you want to enable cgroup support in
# SLURM to be sure that a job can access only the GPUs that were
# allocated to it.
global_var_slurm_taskplugin=task/cgroup
global_var_slurm_proctracktype=proctrack/cgroup

# Create a cloud provider (call it "google-cloud")
[cloud/google-cloud]
provider=google
#****REPLACE WITH YOUR PROJECT ID****
gce_project_id= ****************
#****REPLACE WITH YOUR CLIENT ID****
gce_client_id= ****************
#****REPLACE WITH YOUR SECRET KEY****
gce_client_secret= ****************

# Create a login (call it "google-login")
#
# In contrast to other cloud providers, GCE creates a personal account on each
# VM so you effectively re-use the same `[login/google]` section across
# different VM images.
[login/google-login]
image_user=***********
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
# You can generate the keypair with the command: `gcloud compute config-ssh`
user_key_private=~/.ssh/google_compute_engine
user_key_public=~/.ssh/google_compute_engine.pub

# Bring all of the elements together to define a cluster called "slurm-gpu"
[cluster/slurm-gpu]
cloud=google-cloud
login=google-login
setup=slurm
security_group=default
# CHECK WITH OUTPUT FROM: gcloud compute images list
image_id=ubuntu-1604-xenial-v20180105
flavor=n1-standard-1
ssh_to=frontend
frontend_nodes=1
# adjust size of cluster to taste
compute_nodes=4

# now add 2x GPUs (NVidia Tesla K80) to the compute nodes
# note that as of Nov. 2017, GPU-enabled VMs are available only in few zones
[cluster/slurm-gpu/compute]
accelerator_count=0
# use `gcloud compute accelerator-types list` to see what is available
accelerator_type=nvidia-tesla-k80

 #############################

Thank you very much for any help!

**Comment by riccardomurri** [comment]
It looks like there was a connection error to node `compute003` (you can see it in the `unreachable=1` flag in the summary lines); up to that point everything seems fine (all nodes successfully complete task `lmod: Create required directories`).

It may be just a transient error; I would re-run the setup step and see if it completes correctly:

        elasticluster -v setup slurm-gpu

Are you using pre-emptible instances on Google Cloud?

**Comment by ivandrodri** [comment]
@riccardomurri : thank you very much for your quick reply! 

I run :   elasticluster -v setup slurm-gpu , as you suggested and this is the error I got:

##################################################
Updating cluster `slurm-gpu`...
2021-01-08 07:21:58 7294eb7fead4 elasticluster[1] WARNING UserWarning: Cannot access /home/.elasticluster/storage/562622885803-fn2fuclbhkf8n8tvtvbfeismgsd074n1.apps.googleusercontent.com.oauth.dat: No such file or directory
2021-01-08 07:21:58 7294eb7fead4 elasticluster[1] INFO Determined that provided credentials are not valid.
2021-01-08 07:21:58 7294eb7fead4 elasticluster[1] INFO Attempting to use Google Application Default Credentials.
2021-01-08 07:21:59 7294eb7fead4 elasticluster[1] INFO node 'slurm-gpu-frontend001' state is 'TERMINATED'; no IP address(es)
2021-01-08 07:21:59 7294eb7fead4 elasticluster[1] INFO node 'slurm-gpu-compute001' state is 'TERMINATED'; no IP address(es)
2021-01-08 07:21:59 7294eb7fead4 elasticluster[1] INFO node 'slurm-gpu-compute002' state is 'TERMINATED'; no IP address(es)
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] INFO node 'slurm-gpu-compute003' state is 'TERMINATED'; no IP address(es)
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] INFO node 'slurm-gpu-compute004' state is 'TERMINATED'; no IP address(es)
Configuring cluster `slurm-gpu`...
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] WARNING Ignoring node `frontend001`: No IP address.
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] WARNING Ignoring node `compute001`: No IP address.
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] WARNING Ignoring node `compute002`: No IP address.
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] WARNING Ignoring node `compute003`: No IP address.
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] WARNING Ignoring node `compute004`: No IP address.
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] INFO No inventory file was created.
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] ERROR The cluster hosts are up and running, but Ansible failed to set the cluster up: The cluster does not provide the minimum amount of nodes specified in the configuration. Some nodes are running, but the cluster will not be set up yet. Please change the minimum amount of nodes in the configuration or try to start a new cluster after checking the cloud provider settings.
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] WARNING Cluster `slurm-gpu` not yet configured. Please, re-run `elasticluster setup slurm-gpu` and/or check your configuration

WARNING: YOUR CLUSTER `slurm-gpu` IS NOT READY YET!

Cluster name:     slurm-gpu
Cluster template: slurm-gpu
Default ssh to node: frontend001
- frontend nodes: 1
- compute nodes: 4

To login on the frontend node, run the command:

    elasticluster ssh slurm-gpu

To upload or download files to the cluster, use the command:

    elasticluster sftp slurm-gpu

#############################################

Do you have any idea of what could be the problem? Thanks for any help!

**Comment by riccardomurri** [comment]
Hello, from the log file you posted, it seems that the cluster nodes have been stopped or deleted?

```
2021-01-08 07:21:59 7294eb7fead4 elasticluster[1] INFO node 'slurm-gpu-frontend001' state is 'TERMINATED'; no IP address(es)
2021-01-08 07:21:59 7294eb7fead4 elasticluster[1] INFO node 'slurm-gpu-compute001' state is 'TERMINATED'; no IP address(es)
2021-01-08 07:21:59 7294eb7fead4 elasticluster[1] INFO node 'slurm-gpu-compute002' state is 'TERMINATED'; no IP address(es)
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] INFO node 'slurm-gpu-compute003' state is 'TERMINATED'; no IP address(es)
2021-01-08 07:22:00 7294eb7fead4 elasticluster[1] INFO node 'slurm-gpu-compute004' state is 'TERMINATED'; no IP address(es)
```

Probably your best course of action is now to delete the cluster and start over from scratch:

```
elasticluster stop -f -y slurm-gpu
elasticluster -v start slurm-gpu
```

**Comment by ivandrodri** [comment]
@riccardomurri, thanks for the reply. I have stop and restarted the cluster many times and I got always similar problems. This is the error of the last try:


###################################################

TASK [lmod : Perform OS-specific post-installation] ********************************************************************************************************************************************************
included: /home/elasticluster/share/playbooks/roles/lmod/tasks/postinst-Debian.yml for compute001, compute002, compute003

TASK [lmod : Create required directories] ******************************************************************************************************************************************************************
ok: [compute002] => (item=/etc/profile.d) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", "item": "/etc/profile.d", "mode": "0755", "owner": "root", "path": "/etc/profile.d", "size": 4096, "state": "directory", "uid": 0}
ok: [compute003] => (item=/etc/profile.d) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", "item": "/etc/profile.d", "mode": "0755", "owner": "root", "path": "/etc/profile.d", "size": 4096, "state": "directory", "uid": 0}
ok: [compute001] => (item=/etc/profile.d) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", "item": "/etc/profile.d", "mode": "0755", "owner": "root", "path": "/etc/profile.d", "size": 4096, "state": "directory", "uid": 0}
changed: [compute002] => (item=/etc/csh) => {"ansible_loop_var": "item", "changed": true, "gid": 0, "group": "root", "item": "/etc/csh", "mode": "0755", "owner": "root", "path": "/etc/csh", "size": 4096, "state": "directory", "uid": 0}
changed: [compute003] => (item=/etc/csh) => {"ansible_loop_var": "item", "changed": true, "gid": 0, "group": "root", "item": "/etc/csh", "mode": "0755", "owner": "root", "path": "/etc/csh", "size": 4096, "state": "directory", "uid": 0}
changed: [compute001] => (item=/etc/csh) => {"ansible_loop_var": "item", "changed": true, "gid": 0, "group": "root", "item": "/etc/csh", "mode": "0755", "owner": "root", "path": "/etc/csh", "size": 4096, "state": "directory", "uid": 0}
changed: [compute002] => (item=/etc/csh/login.d) => {"ansible_loop_var": "item", "changed": true, "gid": 0, "group": "root", "item": "/etc/csh/login.d", "mode": "0755", "owner": "root", "path": "/etc/csh/login.d", "size": 4096, "state": "directory", "uid": 0}
changed: [compute003] => (item=/etc/csh/login.d) => {"ansible_loop_var": "item", "changed": true, "gid": 0, "group": "root", "item": "/etc/csh/login.d", "mode": "0755", "owner": "root", "path": "/etc/csh/login.d", "size": 4096, "state": "directory", "uid": 0}
changed: [compute001] => (item=/etc/csh/login.d) => {"ansible_loop_var": "item", "changed": true, "gid": 0, "group": "root", "item": "/etc/csh/login.d", "mode": "0755", "owner": "root", "path": "/etc/csh/login.d", "size": 4096, "state": "directory", "uid": 0}

TASK [lmod : Ensure modulefiles directories are in MODULEPATH] *********************************************************************************************************************************************
skipping: [compute001] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [compute002] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [compute003] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [lmod : Ensure modulefiles directories are in MODULEPATH] *********************************************************************************************************************************************
failed: [compute003] (item={u'dest': u'/etc/profile.d/01-modulepath.sh', u'src': u'etc/profile.d/01-modulepath.sh.j2'}) => {"ansible_loop_var": "item", "item": {"dest": "/etc/profile.d/01-modulepath.sh", "src": "etc/profile.d/01-modulepath.sh.j2"}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100993.83-94044960779942 `\" && echo ansible-tmp-1610100993.83-94044960779942=\"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100993.83-94044960779942 `\" ), exited with result 1", "unreachable": true}
failed: [compute003] (item={u'dest': u'/etc/csh/login.d/01-modulepath.csh', u'src': u'etc/profile.d/01-modulepath.csh.j2'}) => {"ansible_loop_var": "item", "item": {"dest": "/etc/csh/login.d/01-modulepath.csh", "src": "etc/profile.d/01-modulepath.csh.j2"}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100994.36-196346913864755 `\" && echo ansible-tmp-1610100994.36-196346913864755=\"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100994.36-196346913864755 `\" ), exited with result 1", "unreachable": true}
fatal: [compute003]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"ansible_loop_var": "item", "item": {"dest": "/etc/profile.d/01-modulepath.sh", "src": "etc/profile.d/01-modulepath.sh.j2"}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100993.83-94044960779942 `\" && echo ansible-tmp-1610100993.83-94044960779942=\"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100993.83-94044960779942 `\" ), exited with result 1", "unreachable": true}, {"ansible_loop_var": "item", "item": {"dest": "/etc/csh/login.d/01-modulepath.csh", "src": "etc/profile.d/01-modulepath.csh.j2"}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100994.36-196346913864755 `\" && echo ansible-tmp-1610100994.36-196346913864755=\"` echo /home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100994.36-196346913864755 `\" ), exited with result 1", "unreachable": true}]}
changed: [compute001] => (item={u'dest': u'/etc/profile.d/01-modulepath.sh', u'src': u'etc/profile.d/01-modulepath.sh.j2'}) => {"ansible_loop_var": "item", "changed": true, "checksum": "a1e0e15144b05594a30f506b2ab73e0774d2a4ec", "dest": "/etc/profile.d/01-modulepath.sh", "gid": 0, "group": "root", "item": {"dest": "/etc/profile.d/01-modulepath.sh", "src": "etc/profile.d/01-modulepath.sh.j2"}, "md5sum": "327fc3ee357ab83e236ba87e06ccc898", "mode": "0444", "owner": "root", "size": 266, "src": "/home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100993.76-239693617420721/source", "state": "file", "uid": 0}
changed: [compute002] => (item={u'dest': u'/etc/profile.d/01-modulepath.sh', u'src': u'etc/profile.d/01-modulepath.sh.j2'}) => {"ansible_loop_var": "item", "changed": true, "checksum": "a1e0e15144b05594a30f506b2ab73e0774d2a4ec", "dest": "/etc/profile.d/01-modulepath.sh", "gid": 0, "group": "root", "item": {"dest": "/etc/profile.d/01-modulepath.sh", "src": "etc/profile.d/01-modulepath.sh.j2"}, "md5sum": "327fc3ee357ab83e236ba87e06ccc898", "mode": "0444", "owner": "root", "size": 266, "src": "/home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100993.79-29404294410479/source", "state": "file", "uid": 0}
changed: [compute001] => (item={u'dest': u'/etc/csh/login.d/01-modulepath.csh', u'src': u'etc/profile.d/01-modulepath.csh.j2'}) => {"ansible_loop_var": "item", "changed": true, "checksum": "4baf7a0fffd0f2757cc86a64b8c02903ede6740e", "dest": "/etc/csh/login.d/01-modulepath.csh", "gid": 0, "group": "root", "item": {"dest": "/etc/csh/login.d/01-modulepath.csh", "src": "etc/profile.d/01-modulepath.csh.j2"}, "md5sum": "1fd24b264c095632ed2ce3fb8170a4ef", "mode": "0444", "owner": "root", "size": 266, "src": "/home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100997.51-201732368093889/source", "state": "file", "uid": 0}
changed: [compute002] => (item={u'dest': u'/etc/csh/login.d/01-modulepath.csh', u'src': u'etc/profile.d/01-modulepath.csh.j2'}) => {"ansible_loop_var": "item", "changed": true, "checksum": "4baf7a0fffd0f2757cc86a64b8c02903ede6740e", "dest": "/etc/csh/login.d/01-modulepath.csh", "gid": 0, "group": "root", "item": {"dest": "/etc/csh/login.d/01-modulepath.csh", "src": "etc/profile.d/01-modulepath.csh.j2"}, "md5sum": "1fd24b264c095632ed2ce3fb8170a4ef", "mode": "0444", "owner": "root", "size": 266, "src": "/home/ivan.rodriguez/.ansible/tmp/ansible-tmp-1610100997.65-203926456667515/source", "state": "file", "uid": 0}

NO MORE HOSTS LEFT *****************************************************************************************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************************************************
compute001                 : ok=99   changed=55   unreachable=0    failed=0    skipped=70   rescued=0    ignored=0   
compute002                 : ok=99   changed=55   unreachable=0    failed=0    skipped=70   rescued=0    ignored=0   
compute003                 : ok=98   changed=54   unreachable=1    failed=0    skipped=70   rescued=0    ignored=0   
frontend001                : ok=139  changed=91   unreachable=0    failed=0    skipped=70   rescued=0    ignored=0   

2021-01-08 10:16:41 74230bdce98e elasticluster[1] ERROR Command `ansible-playbook --private-key=/home/.ssh/google_compute_engine /home/elasticluster/share/playbooks/main.yml --inventory=/home/.elasticluster/storage/slurm-gpu.inventory --become --become-user=root -v -e @extra_vars.yml` failed with exit code 2.
2021-01-08 10:16:41 74230bdce98e elasticluster[1] WARNING The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup`.
2021-01-08 10:16:41 74230bdce98e elasticluster[1] WARNING Cluster `slurm-gpu` not yet configured. Please, re-run `elasticluster setup slurm-gpu` and/or check your configuration

WARNING: YOUR CLUSTER `slurm-gpu` IS NOT READY YET!

Cluster name:     slurm-gpu
Cluster template: slurm-gpu
Default ssh to node: frontend001
- frontend nodes: 1
- compute nodes: 4

To login on the frontend node, run the command:

    elasticluster ssh slurm-gpu

To upload or download files to the cluster, use the command:

    elasticluster sftp slurm-gpu

########################################


And when I run: ./elasticluster.sh setup slurm-gpu


###########################################

Updating cluster `slurm-gpu`...
2021-01-08 10:18:14 e6b4b17a1aa2 elasticluster[1] WARNING UserWarning: Cannot access /home/.elasticluster/storage/562622885803-fn2fuclbhkf8n8tvtvbfeismgsd074n1.apps.googleusercontent.com.oauth.dat: No such file or directory
2021-01-08 10:18:16 e6b4b17a1aa2 elasticluster[1] WARNING Ignoring error updating information on node name=`compute004`, id=`None`, ips=[], connection_ip=`None`: could not retrieve the ip address for node: no associated instance id
Configuring cluster `slurm-gpu`...
2021-01-08 10:18:16 e6b4b17a1aa2 elasticluster[1] WARNING Ignoring node `compute004`: No IP address.

PLAY [Prepare VM for running Ansible] **********************************************************************************************************************************************************************

TASK [Ensure Python is installed] **************************************************************************************************************************************************************************
fatal: [compute003]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Received disconnect from 104.154.114.135 port 22:2: Too many authentication failures\r\nDisconnected from 104.154.114.135 port 22", "unreachable": true}
skipping: [compute001]
skipping: [frontend001]
skipping: [compute002]

NO MORE HOSTS LEFT *****************************************************************************************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************************************************
compute001                 : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
compute002                 : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
compute003                 : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
frontend001                : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

2021-01-08 10:18:25 e6b4b17a1aa2 elasticluster[1] ERROR Command `ansible-playbook --private-key=/home/.ssh/google_compute_engine /home/elasticluster/share/playbooks/main.yml --inventory=/home/.elasticluster/storage/slurm-gpu.inventory --become --become-user=root -e @extra_vars.yml` failed with exit code 2.
2021-01-08 10:18:25 e6b4b17a1aa2 elasticluster[1] WARNING The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup`.
2021-01-08 10:18:25 e6b4b17a1aa2 elasticluster[1] WARNING Cluster `slurm-gpu` not yet configured. Please, re-run `elasticluster setup slurm-gpu` and/or check your configuration

WARNING: YOUR CLUSTER `slurm-gpu` IS NOT READY YET!

Cluster name:     slurm-gpu
Cluster template: slurm-gpu
Default ssh to node: frontend001
- frontend nodes: 1
- compute nodes: 4

To login on the frontend node, run the command:

    elasticluster ssh slurm-gpu

To upload or download files to the cluster, use the command:

    elasticluster sftp slurm-gpu

#######################################################


I don't know what is going on...should I try with another config file example?

**Comment by riccardomurri** [comment]
I have tried to reproduce your issue, and -indeed- at some point one of the nodes becomes unreachable.

Re-trying after that fails with this error message:

```
2021-01-08 14:46:06 rmurri1 elasticluster[471664] DEBUG Trying to connect to host compute004 using IP address 35.188.126.88 ...
Unknown exception: q must be exactly 160, 224, or 256 bits long
Traceback (most recent call last):
  File "/home/rmurri/.virtualenvs/elasticluster/lib/python3.8/site-packages/paramiko/transport.py", line 2109, in run
    handler(self.auth_handler, m)
  File "/home/rmurri/.virtualenvs/elasticluster/lib/python3.8/site-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
    sig = self.private_key.sign_ssh_data(blob)
  File "/home/rmurri/.virtualenvs/elasticluster/lib/python3.8/site-packages/paramiko/dsskey.py", line 108, in sign_ssh_data
    key = dsa.DSAPrivateNumbers(
  File "/home/rmurri/.virtualenvs/elasticluster/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 250, in private_key
    return backend.load_dsa_private_numbers(self)
  File "/home/rmurri/.virtualenvs/elasticluster/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 852, in load_dsa_private_numbers
    dsa._check_dsa_private_numbers(numbers)
  File "/home/rmurri/.virtualenvs/elasticluster/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 147, in _check_dsa_private_numbers
    _check_dsa_parameters(parameters)
  File "/home/rmurri/.virtualenvs/elasticluster/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 139, in _check_dsa_parameters
    raise ValueError("q must be exactly 160, 224, or 256 bits long")
ValueError: q must be exactly 160, 224, or 256 bits long
```

I must investigate what is going on here, it seems Python's `cryptography` module and Google Cloud do not agree on permissible DSA parameters.

**Comment by riccardomurri** [comment]
Forget my last comment: it's related to a [bug in Paramiko][1] which was however triggered by my local SSH keys, and does not seem like the root cause of this issue.  

I can confirm that when I try to start a cluster on GCP, sooner or later one or more worker nodes cuts the connection and won't allow SSH anymore.

Can you please try again confirm this is the behavior you observe:

1. Stop any running clusters: `elasticluster stop -y slurm-gpu`
 2. Start a new one: `elasticluster -v start slurm-gpu`
 3. When it fails, run this command and then post the final ~100 lines of the output: `elasticluster -vvvvv start slurm-gpu`


[1]: https://github.com/paramiko/paramiko/pull/1606

**Comment by ivandrodri** [comment]
@riccardomurri: thanks for the information! I have solved the problem now. I cleaned my public keys in google-cloud metadata and create a new one and the cluster works now. However I have another issue now: 

When I stop the cluster and start it again I am able to ssh to the cluster but when I try to get sinfo or get an interactive session like:

srun -N 2 --pty bash -i

I get the following error:

srun: error: Unable to allocate resources: Zero Bytes were transmitted or received

Do you know what is going on?

Thanks for any help!

**Comment by riccardomurri** [comment]
Hello @ivandrodri I'm glad the first issue is now solved!  Regarding your report:

> When I stop the cluster and start it again I am able to ssh to the cluster but when I try to get sinfo or get an interactive session like:
> ```
> srun -N 2 --pty bash -i
> ```
> I get the following error:
> ```
> srun: error: Unable to allocate resources: Zero Bytes were transmitted or received
> ```

Did the cluster configuration complete correctly?  If it did, you can try this: login on the frontend node and issue this command:

```
sudo systemctl restart slurmctld
```

If it still does not work, please run the following commands and post their output:

```
sudo systemctl status slurmctld
sudo systemctl status slurmdbd
```
